apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: image-sync
spec:
  serviceName: "image-sync"
  replicas: 3
  selector:
    matchLabels:
      app: image-sync
  template:
    metadata:
      labels:
        app: image-sync
    spec:
      imagePullSecrets:
      - name: ocir-credentials2
      containers:
      - name: image-sync-container
        image: <region>.ocir.io/<tenancy>/<namespace>/<image-name>:<tag>
        imagePullPolicy: Always
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: secret-access-key
          - name: AWS_DEFAULT_REGION
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: default-region
          - name: OCI_TENANCY
            valueFrom:
              secretKeyRef:
                name: oci-credentials
                key: OCI_TENANCY
          - name: OCI_USERNAME
            valueFrom:
              secretKeyRef:
                name: oci-credentials
                key: OCI_USERNAME
          - name: OCI_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: oci-credentials
                key: OCI_AUTH_TOKEN
          - name: OCI_REGION
            valueFrom:
              secretKeyRef:
                name: oci-credentials
                key: OCI_REGION
          - name: OCI_REPO_REGION_KEY
            valueFrom:
              secretKeyRef:
                name: oci-credentials
                key: OCI_REPO_REGION_KEY
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "8Gi"
            cpu: "2"
        volumeMounts:
        - name: skopeo-temp
          mountPath: /tmp
        - name: skopeo-config
          mountPath: /root/.containers
  volumeClaimTemplates:
  - metadata:
      name: skopeo-temp
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: oci-bv
      resources:
        requests:
          storage: 20Gi
  - metadata:
      name: skopeo-config
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: oci-bv
      resources:
        requests:
          storage: 1Gi